services:
  whatsapp-agent:
    build:
      context: .
    container_name: whatsapp-agent
    restart: unless-stopped
    environment:
      PORT: "3000"

      DB_HOST: "65.109.27.58"
      DB_PORT: "55432"
      DB_USER: "postgres"
      DB_PASSWORD: "ayYtneAT6CuKks"
      DB_NAME: "whatsapp_agent"

      # Appeler WAHA via le r√©seau docker (service name = waha)
      WAHA_BASE_URL: "http://waha:3000"
      WAHA_API_KEY: "BekoWahaKey_2025_Abidjan_9xPqL7vT2"

      # URL n8n
      N8N_COMMAND_BOT_URL: "https://n8n.srv853938.hstgr.cloud/webhook/commandBot"

    
    ports:
      - "3002:3000/tcp"
    networks:
      - appnet

networks:
  appnet:
    external: true
    name: appnet
