services:
   whatsapp-agent:
    build: .
    container_name: whatsapp-agent
    restart: unless-stopped
    environment:
      PORT: "3000"
      WAHA_API_URL: "http://waha:3000"
      WAHA_API_KEY: "BekoWahaKey_2025_Abidjan_9xPqL7vT2"
      COMMANDBOT_API_URL: "https://n8n.srv853938.hstgr.cloud/webhook/commandBot"
      DB_HOST: "65.109.27.58"
      DB_PORT: "55432"
      DB_USER: "postgres"
      DB_PASSWORD: "ayYtneAT6CuKks"
      DB_NAME: "whatsapp_agent"
    depends_on:
      - waha
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
